### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by bkoty** [black-ops-drivers/control4-myq#1]
tried with multiple emails and passwords cant get the login to work.  Some passes had ! some had ? also tried passwords with just letters and numbers, also tried emails that ended in .edu and some with .com nothing working

**Comment by black-ops-drivers** [comment]
Can set the log level to Trace and log mode to Print and post the logs here?

**Comment by black-ops-drivers** [comment]
This was fixed by #2.
