### ISSUE TITLE
Feature Request: Still Open event

### ISSUE THREAD

**Issue by Anks329** [black-ops-drivers/control4-myq#3]
Would it be possible to add a "still open" event to this driver? If the garage door is left open for greater than x seconds a "still open" event is fired. This will enable programming (email alerts) based on this event.

Example of this can be seen in the "Relay Garage Door Controller (OS2.9+)" driver.  I think the following is the relevant code from lua file: 

[snip.txt](https://github.com/black-ops-drivers/control4-myq/files/12450964/snip.txt)

**Comment by black-ops-drivers** [comment]
Yes this should be an easy addition. I will try to find to update it this week.

**Comment by black-ops-drivers** [comment]
Your drivers should auto update (or you can force it to update in the controller actions), then you can use the new `Still Open` event.

**Comment by Anks329** [comment]
Thank you for the quick feature update. Tested the updated driver and the still open event works flawlessly!
