### ISSUE TITLE
Getting ERROR: "Authentication Failed; check logs for more details"

### ISSUE THREAD

**Issue by ajguerre1** [black-ops-drivers/control4-myq#6]
Driver was working correctly. Then I started getting the authentication error. Below is the LUA output with Log Level 4- Debug:

Fri Sep  8 10:40:06 2023 [INFO ]: Fetching devices from the myQ API (timer expired)
Fri Sep  8 10:40:06 2023 [DEBUG]: Minting a new myQ API OAuth token...
Fri Sep  8 10:40:06 2023 [ERROR]: Authentication failed; authentication failed; authorize response was missing cookie
Fri Sep  8 10:40:06 2023 [ERROR]: An error occurred refreshing devices; authentication failed; authorize response was missing cookie

Driver version 20230902

Let me know what other info you need to help troubleshoot this issue.

**Comment by black-ops-drivers** [comment]
Fixed in #7, driver version v20230908
